export const getDecks = () => {
    return [
        {
            name: "romedeck",
            texture: "romedeck",
            character: "rome_general",
            title: "romedeck_title",
        },
        {
            name: "greecedeck",
            texture: "greecedeck",
            character: "greece_general",
            title: "greecedeck_title",
        },
        {
            name: "romedeck",
            texture: "romedeck",
            character: "rome_general",
            title: "romedeck_title",
        },
        {
            name: "greecedeck",
            texture: "greecedeck",
            character: "greece_general",
            title: "greecedeck_title",
        },
        {
            name: "romedeck",
            texture: "romedeck",
            character: "rome_general",
            title: "romedeck_title",
        },
        {
            name: "greecedeck",
            texture: "greecedeck",
            character: "greece_general",
            title: "greecedeck_title",
        }
    ]
}


export const getCards = () => {
    // type: 1 = mele, 2 = ranged, 3 = hero, 4 = special
    return [
        {
            name: "Psilos",
            texture: "hoplita-espartano",
            deck: "Roman Army",
            description: "Standard heavy Roman foot soldier",
            symbol: "RO",
            type: 1,
            effect: "",
            point: 6,
            level: 1,
        },
        {
            name: "Centurion",
            texture: "falangita-macedonio",
            deck: "Roman Army",
            description: "Elite leader, boosts nearby troops",
            symbol: "RO",
            type: 1,
            effect: "",
            point: 8,
            level: 3,
        },
        {
            name: "Praetorian Guard",
            texture: "guerrenro-espartano",
            deck: "Roman Army",
            description: "Emperor’s guard, heavily armored",
            symbol: "RO",
            type: 1,
            effect: "",
            point: 9,
            level: 4,
        },
        {
            name: "Gladiator",
            texture: "hoplita-espartano",
            deck: "Roman Army",
            description: "	Agile but unpredictable fighter",
            symbol: "RO",
            type: 1,
            effect: "",
            point: 5,
            level: 2,
        },
        {
            name: "Auxilia Infantry",
            texture: "hoplita-espartano",
            deck: "Roman Army",
            description: "Non-citizen soldiers, light infantry",
            symbol: "RO",
            type: 1,
            effect: "",
            point: 4,
            level: 1,
        },
        {
            name: "Archer",
            texture: "hoplita-espartano",
            deck: "Roman Army",
            description: "Light, mobile archer unit",
            symbol: "RO",
            type: 1,
            effect: "",
            point: 4,
            level: 1,
        },
        {
            name: "Balista",
            texture: "hoplita-espartano",
            deck: "Roman Army",
            description: "Large bolt-throwing siege engine",
            symbol: "RO",
            type: 1,
            effect: "",
            point: 7,
            level: 3,
        },
        {
            name: "Slingers",
            texture: "hoplita-espartano",
            deck: "Roman Army",
            description: "Light troops with slings",
            symbol: "RO",
            type: 1,
            effect: "",
            point: 3,
            level: 1,
        },
        {
            name: "Legionary",
            texture: "hoplita-espartano",
            deck: "Roman Army",
            description: "Standard heavy Roman foot soldier",
            symbol: "RO",
            type: 1,
            effect: "",
            point: 6,
            level: 1,
        },
        {
            name: "Centurion",
            texture: "hoplita-espartano",
            deck: "Roman Army",
            description: "Elite leader, boosts nearby troops",
            symbol: "RO",
            type: 1,
            effect: "",
            point: 8,
            level: 3,
        },
        {
            name: "Praetorian Guard",
            texture: "hoplita-espartano",
            deck: "Roman Army",
            description: "Emperor’s guard, heavily armored",
            symbol: "RO",
            type: 1,
            effect: "",
            point: 9,
            level: 4,
        },
        {
            name: "Gladiator",
            texture: "hoplita-espartano",
            deck: "Roman Army",
            description: "	Agile but unpredictable fighter",
            symbol: "RO",
            type: 1,
            effect: "",
            point: 5,
            level: 2,
        },
        {
            name: "Auxilia Infantry",
            texture: "hoplita-espartano",
            deck: "Roman Army",
            description: "Non-citizen soldiers, light infantry",
            symbol: "RO",
            type: 1,
            effect: "",
            point: 4,
            level: 1,
        },
        {
            name: "Archer",
            texture: "hoplita-espartano",
            deck: "Roman Army",
            description: "Light, mobile archer unit",
            symbol: "RO",
            type: 1,
            effect: "",
            point: 4,
            level: 1,
        },
        {
            name: "Balista",
            texture: "hoplita-espartano",
            deck: "Roman Army",
            description: "Large bolt-throwing siege engine",
            symbol: "RO",
            type: 1,
            effect: "",
            point: 7,
            level: 3,
        },
        {
            name: "Slingers",
            texture: "hoplita-espartano",
            deck: "Roman Army",
            description: "Light troops with slings",
            symbol: "RO",
            type: 1,
            effect: "",
            point: 3,
            level: 1,
        },
        {
            name: "Psilos",
            texture: "hoplita-tebano",
            deck: "Greek Army",
            description: " Light-footed skirmishers, armed with simple javelins and leather armor.",
            symbol: "GE",
            type: 1,
            effect: "",
            point: 3,
            level: 1,
        },
        {
            name: "Peltast",
            texture: "oficial-ateniense",
            deck: "Greek Army",
            description: "Agile warriors carrying crescent shields and hurling javelins with deadly",
            symbol: "GE",
            type: 1,
            effect: "",
            point: 5,
            level: 1,
        },
        {
            name: "Hoplite",
            texture: "hoplita-platea",
            deck: "Greek Army",
            description: "Core of the Greek army — disciplined spearmen with bronze shields and formation tactics.",
            symbol: "GE",
            type: 1,
            effect: "",
            point: 7,
            level: 2,
        },
        {
            name: "Lochagos",
            texture: "hoplita-ateniense",
            deck: "Greek Army",
            description: "Veteran Hoplites elevated to lead smaller units with authority and precision.",
            symbol: "GE",
            type: 1,
            effect: "",
            point: 9,
            level: 2,
        },
        {
            name: "Hippeis",
            texture: "hippeis",
            deck: "Greek Army",
            description: "Noble-born riders trained from youth, used for mobility and backline strikes.",
            symbol: "GE",
            type: 3,
            effect: "",
            point: 8,
            level: 3,
        },
        {
            name: "Oracle of Delphi",
            texture: "hoplita-tespio",
            deck: "Greek Army",
            description: "Enigmatic priestess wielding divine foresight to inspire and confuse.",
            symbol: "GE",
            type: 3,
            effect: "",
            point: 3,
            level: 3,
        },
        {
            name: "Ekdromoi",
            texture: "oficial-espartano",
            deck: "Greek Army",
            description: "Light-armored Hoplites trained to break formation and pursue enemies.",
            symbol: "GE",
            type: 1,
            effect: "",
            point: 7,
            level: 3,
        },
        {
            name: "Sacred Band of Thebes",
            texture: "guerrenro-espartano",
            deck: "Greek Army",
            description: "Legendary unit of paired warriors fighting with unity and unmatched valor.",
            symbol: "GE",
            type: 1,
            effect: "",
            point: 11,
            level: 4,
        },
        {
            name: "Achilles",
            texture: "hoplita-espartano",
            deck: "Greek Army",
            description: "The invulnerable champion of the Iliad, armored in gold and driven by fate.",
            symbol: "GE",
            type: 1,
            effect: "",
            point: 15,
            level: 5,
        },
    ]
}